### ISSUE TITLE
Tweaks to New Game flow

### ISSUE THREAD

**Issue by connor-g** [pspeter3/epidemia#13]
- Replace Gear icon with Edit.svg (from Feather)
- Change "Save" button to "New Game"
- Add "Cancel" button next to "New Game"

**Comment by pspeter3** [comment]
What does the cancel button do?

**Comment by connor-g** [comment]
Backs out of the screen without resetting the game. Is there any other way to do that if you were mid-game and accidentally opened this screen?

**Comment by pspeter3** [comment]
Yeah, you could click any of the tabs. The tabs still display while in the Settings screen for that reason. 

![settings](https://user-images.githubusercontent.com/607701/40441916-35aac2de-5e77-11e8-9662-bf466920d5ed.png)

**Comment by connor-g** [comment]
And even knowing that, if I were to edit the deck contents and then tap into another tab I wouldn't know what to expect. Would it reset the current game state, or throw out my changes?

**Comment by pspeter3** [comment]
Throw out your changes.
