### ISSUE TITLE
Add navigation UI

### ISSUE THREAD

**Issue by pspeter3** [pspeter3/epidemia#50]
Make the navigation clear to others by providing back buttons and screen names.

**Comment by pspeter3** [comment]
@connor-g I am planning to use `compass` or `life-buoy` for the logo. Also do you think `arrow-left` `chevron-left` or `chevrons-left` is a better back button?

https://feathericons.com/

**Comment by connor-g** [comment]
I like `chevron-left` for the back button. And my vote is for `life-body` as the logo.
