### ISSUE TITLE
Add "Standard Button" to Settings

### ISSUE THREAD

**Issue by pspeter3** [pspeter3/epidemia#51]
Make it easy to play Standard Pandemic with this tool.

**Comment by pspeter3** [comment]
@connor-g do you know what the standard configuration is?

**Comment by connor-g** [comment]
Based on https://boardgamegeek.com/wiki/page/Pandemic_series and the fact that the board has 48 cities on it, it looks like the standard is: 

- 53 player cards (48 cities + 5 events)
- 6 epidemics
- 1x 48 city infection cards:

1. - San Francisco
2. - Chicago
3. - Atlanta
4. - Toronto
5. - Washington
6. - New York
7. - Madrid
8. - London
9. - Paris
10. - Essex
11. - Milan
12. - St. Petersburg
13. - Los Angeles
14. - Miami
15. - Mexico City
16. - Bogota
17. - Lima
18. - Sao Paulo
19. - Santiago
20. - Buenos Aires
21. - Johannesburg
22. - Kinshasa
23. - Lagos
24. - Khartoum
25. - Algiers
26. - Cairo
27. - Istanbul
28. - Moscow
29. - Riyadh
30. - Baghdad
31. - Tehran
32. - Delhi
33. - Karachi
34. - Mumbai
35. - Chennai
36. - Calcutta
37. - Bangkok
38. - Jakarta
39. - Sydney
40. - Ho Chi Minh City
41. - Manila
42. - Hong Kong
43. - Taipei
44. - Osaka
45. - Shanghai
46. - Tokyo
47. - Seoul
48. - Beijing
